import {ImagesIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'
import {BulkUploadInput} from '../components/BulkUploadInput'

export const galleryUploadGroup = defineType({
  name: 'galleryUploadGroup',
  title: 'Gallery Upload Group (Bulk)',
  type: 'document',
  icon: ImagesIcon,
  fields: [
    defineField({
      name: 'titlePrefix',
      title: 'Title Prefix / Base Title',
      type: 'string',
      description: 'Used as the starting title for all images in this group (e.g. "Simple Back Neck Aari Blouse Design"). Each image title will be auto-generated by combining this prefix with the image caption or alternative text.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{type: 'category'}],
      description: 'Select the category that applies to ALL images uploaded in this group.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'images',
      title: 'Images in Group',
      type: 'array',
      of: [
        {
          type: 'image',
          options: {
            hotspot: true,
            accept: 'image/*',
            storeOriginalFilename: true,
          },
          fields: [
            defineField({
              name: 'alt',
              type: 'string',
              title: 'Alternative text',
            }),
            defineField({
              name: 'caption',
              type: 'string',
              title: 'Caption',
            }),
          ]
        }
      ],
      options: {
        layout: 'grid',
      },
      components: {
        input: BulkUploadInput,
      },
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published Date',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'description',
      title: 'Group Description',
      type: 'text',
      description: 'General description for the designs in this group (will default as caption if not specified on individual images).',
    }),
  ],
  preview: {
    select: {
      title: 'titlePrefix',
      category: 'category.title',
      images: 'images',
    },
    prepare(selection) {
      const {title, category, images} = selection
      const count = images ? images.length : 0
      return {
        title: `${title} (${count} images)`,
        subtitle: `Category: ${category || 'None'}`,
        media: images && images.length > 0 ? images[0] : ImagesIcon,
      }
    },
  },
})

export default galleryUploadGroup
